site_name: manta
site_description: Manta Documentation
site_author: Fischer Moseley

repo_url: https://github.com/fischermoseley/manta/

docs_dir: 'doc'

theme:
  name: material
  logo: assets/manta_minimal_border.png
  favicon: assets/manta_with_shadow.png
  features:
    - content.code.copy
    - content.code.annotate

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
    - User Reference:
      - Home: index.md
      - Getting Started: getting_started.md
      - Logic Analyzer Core: logic_analyzer_core.md
      - IO Core: io_core.md
    - Developer Reference:
      - System Architecture: system_architecture.md
      - Tools Used: tools_used.md
      - To Do: todo.md
