[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "manta"
version = "0.0.0"
authors = [
  { name="Fischer Moseley", email="fischerm@mit.edu" },
]
description = "An In-Situ Debugging Tool for Programmable Hardware"
readme = "README.md"
dependencies = [
  'PyYAML',
  'pyserial',
  'pyvcd',
]

requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Development Status :: 2 - Pre-Alpha",
]

[project.urls]
"Homepage" = "https://github.com/fischermoseley/manta"
"Bug Tracker" = "https://github.com/fischermoseley/manta/issues"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
mypkg = ["*.sv", "*.v"]