#
# This file is part of LiteEth.
#
# Copyright (c) 2020-2022 Florent Kermarrec <florent@enjoy-digital.fr>
# SPDX-License-Identifier: BSD-2-Clause

# PHY --------------------------------------------------------------------------
phy:         LiteEthPHYRMII
vendor:      xilinx
toolchain:   vivado

# Core -------------------------------------------------------------------------
refclk_freq: 50e6
clk_freq:    50e6
core:        udp
mac_address: 0x10e2d5000000
dhcp: True
data_width:  8

# UDP Ports --------------------------------------------------------------------
udp_ports:   {
  "udp0": {
    "udp_port"      : 2000,            # Static Params.
    "data_width"    : 32,
    "tx_fifo_depth" : 64,
    "rx_fifo_depth" : 64,
  },
}
