name: build_examples
on: [push]
jobs:
  counter:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Add SSH Keys
        run: |
          mkdir ~/.ssh
          touch ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.LAB_BC_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.LAB_BC_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Install Manta from Source
        run: |
          pip3 install build
          python -m build
          python3 -m pip install .

      - name: Generate Core
        run: manta gen examples/counter/manta.yaml examples/counter/src/debug.sv
      
      - name: Build Verilog
        working-directory: examples/counter
        run: mkdir obj && python3 lab-bc.py