name: build_examples
on: [push]
jobs:
  counter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add SSH Keys
        run: |
          mkdir ~/.ssh
          touch ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.LAB_BC_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.LAB_BC_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Install Manta from Source
        run: |
          pip install setuptools --upgrade
          export DEB_PYTHON_INSTALL_LAYOUT=deb_system
          python3 -m pip install .

      - name: Generate Core
        run: manta gen examples/counter/manta.yaml examples/counter/src/debug.sv
      
      - name: Build Verilog
        working-directory: examples/counter
        run: mkdir obj && python3 lab-bc.py

      - name: Print build.log
        working-directory: examples/counter
        run: cat obj/build.log