name: build_examples
on: [push]
jobs:
  counter:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: python3 manta.py gen examples/counter/ila.yaml
      - name: build
        working-directory: examples/counter
        run: python3 lab-bc.py