name: functional_simulation
on: [push]
jobs:
  uart:
    runs-on: ubuntu-latest
    uses: actions/checkout@v3
    steps:
      - run: sudo apt install iverilog
      - run: iverilog -g2012 -o sim.out test/uart_tb.sv src/uart_tx.sv src/uart_rx.sv
      - run: vvp sim.out