name: run_all_tests
on: [push]
jobs:
  install-iverilog:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install bison flex g++ gcc gperf
      - run: git clone https://github.com/steveicarus/iverilog.git

      - name: autoconf
        run: sh ./autoconf.sh
        working-directory: iverilog/

      - name: configure
        run: ./configure
        working-directory: iverilog/

      - name: make
        run: make -j`nproc`
        working-directory: iverilog/

      - name: make check
        run: make check
        working-directory: iverilog/

      - name: sudo make install
        run: sudo make install
        working-directory: iverilog/