name: run_all_tests
on: [push]
jobs:
  install-iverilog:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install bison flex g++ gcc
      - run: git clone https://github.com/steveicarus/iverilog.git

      - name: autoconfigure
        run: sh ./autoconf.sh
        working-directory: iverilog/

      - name: configure
        run: ./configure
        working-directory: iverilog/

      - name: build
        run: make
        working-directory: iverilog/
        
      - run: make check
      - run: sudo make install