name: run_all_tests
on: [push]
jobs:
  install-iverilog:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install bison flex g++ gcc
      - run: git clone https://github.com/steveicarus/iverilog.git
      - run: cd iverilog/
      - run: ./configure
      - run: make
      - run: sudo make install